version: 0.2
phases:
  install: #Instalar pynamodb
    runtime-versions:
      python: 3.9

  build:
    commands:
      - sam build
      - export BUCKET=s3-bucket-913408962111
      - sam package --s3-bucket $BUCKET --output-template-file template.yaml

artifacts:
  type: zip
  files:
    - template.yaml