version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "infraestructura"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tlvrrfnsxal8"
s3_prefix = "infraestructura"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
